# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('臺灣言語資料庫', '0007_auto_20161121_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kaldi辨識結果',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('辨識出問題', models.BooleanField()),
                ('分詞', models.TextField(blank=True)),
                ('影音', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Kaldi辨識結果', to='臺灣言語資料庫.影音表')),
            ],
        ),
    ]
