# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語服務', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaldi辨識結果',
            name='辨識好猶未',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kaldi辨識結果',
            name='辨識出問題',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kaldi辨識結果',
            name='辨識好猶未',
            field=models.BooleanField(default=False),
        ),
    ]
