# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語服務', '0003_kaldi對齊結果'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kaldi語料對齊',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('臺灣言語服務.kaldi對齊結果',),
        ),
        migrations.AddField(
            model_name='kaldi對齊結果',
            name='壓縮檔',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
