# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import 臺灣言語服務.models檢查


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語服務', '0004_auto_20170427_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='訓練過渡格式',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('來源', models.CharField(db_index=True, max_length=100)),
                ('年代', models.CharField(db_index=True, max_length=30)),
                ('種類', models.CharField(choices=[('字詞', '字詞'), ('語句', '語句')], db_index=True, max_length=100)),
                ('影音所在', models.FilePathField(blank=True, max_length=200, null=True, validators=[臺灣言語服務.models檢查.檢查敢是影音檔案, 臺灣言語服務.models檢查.檢查敢是wav])),
                ('影音語者', models.CharField(blank=True, max_length=100)),
                ('文本', models.TextField(blank=True, validators=[臺灣言語服務.models檢查.檢查敢是分詞])),
                ('聽拍', jsonfield.fields.JSONField(blank=True, null=True, validators=[臺灣言語服務.models檢查.檢查聽拍內底欄位敢有夠])),
                ('外語', models.TextField(blank=True, validators=[臺灣言語服務.models檢查.檢查敢是分詞])),
            ],
        ),
    ]
