# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('臺灣言語服務', '0005_訓練過渡格式'),
    ]

    operations = [
        migrations.RenameField(
            model_name='訓練過渡格式',
            old_name='外語',
            new_name='外文',
        ),
    ]
